pipeline_name: anomaly_gui_run
stages:
- name: load_data
  type: csv_loader
  params:
    source: C:\ml-orchestrator\ml-orchestrator\data\fraud.csv
    target_column: Class
- name: preprocess
  type: tabular_preprocess
  params:
    target_column: Class
    task_type: anomaly
    scale_numeric: true
    encode_categoricals: true
    test_size: 0.2
- name: model
  type: anomaly_isolation_forest
  params: {}
