pipeline_name: classification_gui_run
stages:
- name: load_data
  type: csv_loader
  params:
    source: C:\ml-orchestrator\ml-orchestrator\data\titanic.csv
    target_column: Survived
- name: preprocess
  type: tabular_preprocess
  params:
    target_column: Survived
    task_type: classification
    scale_numeric: true
    encode_categoricals: true
    test_size: 0.10000000000000002
- name: model
  type: classification_logreg
  params: {}
